repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
        exclude: &preCommitHooks ^frontend/.*$|^svc/.*$
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: *preCommitHooks
      - id: check-yaml
        exclude: *preCommitHooks
      - id: detect-aws-credentials
      - id: detect-private-key
        exclude: *preCommitHooks
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args:
          - '--fix=auto'
      - id: trailing-whitespace
